### ISSUE TITLE
Empty DPI stats

### ISSUE THREAD

**Issue by ausfestivus** [unpoller/unpoller#834]
Raised this in Discord [here](https://discord.com/channels/184509568867368963/598703441933500416/1373557929491300384).

Including details here for completeness.

> How much do we love questions related to empty DPI graphs?
> 
> Ive run through all the suggestions at https://unpoller.com/docs/help/common
> 
> My env:
> docker via docker compose on Linux with Prometheus and Grafana, all latest container releases,
> unpoller debug logs not showing any errors,
> unpoller debug logs showing minimal data return from the Network Controller API for DPI status I think: 2025/05/18 07:01:01.759511 updateweb.go:223: [DEBUG] Requested https://homegw.2ld/proxy/network/api/s/default/stat/stadpi: elapsed 3ms, returned 30 bytes,
> Unpoller container environment: config:,
>     environment:
>       - UP_INFLUXDB_DISABLE=true
>       - UP_POLLER_DEBUG=true
>       - UP_UNIFI_DYNAMIC=false
>       - UP_PROMETHEUS_HTTP_LISTEN=0.0.0.0:9130
>       - UP_PROMETHEUS_NAMESPACE=unpoller
>       - UP_UNIFI_CONTROLLER_0_PASS=${UP_UNIFI_CONTROLLER_0_PASS}
>       - UP_UNIFI_CONTROLLER_0_SAVE_ALARMS=true
>       - UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES=true
>       - UP_UNIFI_CONTROLLER_0_SAVE_DPI=true
>       - UP_UNIFI_CONTROLLER_0_SAVE_EVENTS=true
>       - UP_UNIFI_CONTROLLER_0_SAVE_IDS=false
>       - UP_UNIFI_CONTROLLER_0_SAVE_SITES=true
>       - UP_UNIFI_CONTROLLER_0_URL=${UP_UNIFI_CONTROLLER_0_URL}
>       - UP_UNIFI_CONTROLLER_0_USER=${UP_UNIFI_CONTROLLER_0_USER}
> 
> Unifi gateway is a UDM-SE running FW 4.2.12 and Network App 9.2.79,
> Other dashboards have data/stats no problem.

Confirming that DPI is enabled in my Network app:

![Image](https://github.com/user-attachments/assets/6432c60d-28e7-49c8-b2af-0051a4f7bd28)

As noted by others in the above thread:

Xenastry:
> Having the same behavior. Assuming the rebrand of DPI is "Device and Traffic Identification" 
>
>When trying to pull the data myself at https://<controller-ip>/proxy/network/api/s/default/stat/sitedpi I get blank json {"meta":{"rc":"ok"},"data":[{}]}

I will get a dump of the new endpoint shortly and add it here in a bit. Just wanted to get this Issue onto the table.

**Comment by ausfestivus** [comment]
Can confirm I am seeing the same API returns as Xenastry. Ive done some poking around and cant seem to find a way to get the dump youre asking for. What I did find though, and I dont know if this helps you or not:

* Some sort of community wiki which has some details about the APIs: [https://ubntwiki.com/products/software/unifi-controller/api](https://ubntwiki.com/products/software/unifi-controller/api)
* Results of my poking at the DPI endpoint per the above wiki information:

<img width="635" alt="Image" src="https://github.com/user-attachments/assets/02c2960a-8deb-4695-83b9-d44d535831e7" />

If you need me try/provide anything else lemme know, happy to help if it means I can ignore work shenanigans.

**Comment by SpOxDK** [comment]
I can confirm the behaviour as well. 
DPI data has been shown in Grafana perfectly for months and the issue started the minute I upgraded to Unifi Network 9.1.120.

Polling the https://[UDMPRO]/proxy/network/api/s/default/stat/sitedpi URL, returns an empty array.

I am happy to do any research, debugging or whatever, just let me know. 😊

**Comment by ausfestivus** [comment]
Just realised, I wonder if Ubiquiti even realise it's broken. Will raise a support request and see what they have to say.

**Comment by ausfestivus** [comment]
Ubiquiti support has responded this morning. Here is what they have stated:

> Hello Andrew,
>  
> Thank you for the report.
> Upon checking internally, we only support the endpoints listed in the API documentation available within the console.
> 
> However, we appreciate you sharing this feedback and the community discussion. It’s been noted and passed along to the relevant team.
> Best,
> 
> UI Support
> Ubiquiti Inc.

I have requested they provide a link/reference to a publicly accessible statement about this policy and/or a reference to patch notes where this is mentioned.

Feels dirty to me. Offer an API endpoint and then decide it's not supported anymore without any deprecation notice. Thats not how API lifecycle management works.

**Comment by davidnewhall** [comment]
> I wonder if Ubiquiti even realise it's broken

Is there actually something broken in your UniFi setup/configs? If there's not, they're going to tell you they don't support their API.

They probably did this on purpose. They don't like when the community makes better products than theirs.

**Comment by ausfestivus** [comment]
> I have requested they provide a link/reference to a publicly accessible statement about this policy and/or a reference to patch notes where this is mentioned.

Ubiquity have not done this. They HAVE thanked me for my feedback though.

I suspect that this issue in Network Application 9.1 and 9.2 won't be resolved until the DPI API endpoint appears in the API documentation.

**Comment by fnetto** [comment]
I just tried this with Network 9.2.87 and yeah, DPI metric is not available.

**Comment by ChristianSatzky** [comment]
Is there still working on a solution or is there already a solution?

**Comment by ausfestivus** [comment]
Hey @platinummonkey what's this project's policy regarding issue closure due to staleness and ageing?

I have my own personal view about the practice but this is your project so your rules.

**Comment by platinummonkey** [comment]
Hm, capturing dumps with the -j option would help. Maybe they are somewhere else in the api or inspecting what their UI is doing.

**Comment by ngreatorex** [comment]
Being a fresh UniFi adopter, I don't know what the data the old endpoint returned looked like. But from what I can see, the UniFi Network UI now uses the following request (resposne snipped to just 1 client and 2 apps):

```
GET /proxy/network/v2/api/site/default/traffic?start=1760446795946&end=1760533195946&includeUnidentified=true
```
```json
{
    "client_usage_by_app": [
        {
            "client": {
                "fingerprint": {
                    "computed_dev_id": 4720,
                    "computed_engine": 0,
                    "dev_cat": 13,
                    "dev_family": 7,
                    "dev_id": 3465,
                    "dev_id_override": 4720,
                    "dev_vendor": 576,
                    "has_override": true,
                    "os_name": 1
                },
                "hostname": "P110",
                "is_wired": false,
                "mac": "b4:b0:24:95:xx:xx",
                "name": "P110",
                "oui": "TP-Link Corporation Limited",
                "wlanconf_id": "680d2fdfb46ca96f5018xxxx"
            },
            "usage_by_app": [
                {
                    "activity_seconds": 145,
                    "application": 185,
                    "bytes_received": 406402,
                    "bytes_transmitted": 237194,
                    "category": 20,
                    "total_bytes": 643596
                },
                {
                    "application": 65535,
                    "bytes_received": 226944,
                    "bytes_transmitted": 94614,
                    "category": 255,
                    "total_bytes": 321558
                }
            ]
        }
    ],
    "total_usage_by_app": [
        {
            "application": 185,
            "bytes_received": 7071475371,
            "bytes_transmitted": 1216044669,
            "category": 20,
            "client_count": 53,
            "total_bytes": 8287520040
        },
        {
            "application": 65535,
            "bytes_received": 263804027,
            "bytes_transmitted": 299134012,
            "category": 255,
            "client_count": 64,
            "total_bytes": 562938039
        }
    ]
}
```

Not sure how close to the old format that is?

**Comment by amoksworld** [comment]
Last time I lost DPI data I noticed the controller updated to a new version, so my thougt was some change in API again.
Then I realised, that the network controller software stoped showing DPI data and traffic flows, too.
I opened a ticket at ui support and surprise: they told me my gateway (USG-PRO-4) was not supported anymore.
Bought a new gateway some days ago (UXG-MAX) and DPI data is available again in the unifi controller.
Sadly not in the grafana dashboards - so I landed here.
Set unpoller to debug mode and watching syslog to find nothing interesting but only entries saying:
`[INFO] UniFi Metrics Recorded. Site: 1, Client: 69, Gateways: 1, UAP: 4, USW: 3, IDs/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 1/0, Point: 179, Fields: 4641, Err: 0, Dur: 42ms`
and wonder what to do now...

**Comment by kambiz-aghaiepour** [comment]
Same still with Network: 9.5.21.   If `/proxy/network/v2/api/site/default/traffic` is actually legit and differs from the "old" way, some code changes are probably in order to unpoller to allow for populating prometheus and InfluxDB.  I have not read through the code, (nor am I proficient at go) but I suspect code changes are necessary.  Sadly I have not had the pleasure of seeing the DPI stats in my grafana for my home setup, but I love the rest of the graphs I've seen!

**Comment by bondskin** [comment]
Chiming in there. 
All Unpoller Grafana dashboards are fine, except DPI ("no data")

UDM-SE 5.0.5 & UNA 10.0.162

**Comment by euri911** [comment]
I've never managed to have DPI stats in Grafana.

Current setup:
Gateway: UXG-Max, firmware 4.3.1
Controller: CloudKey+ Gen2 with UnifiOS 4.4.3
Unifi Network version: 10.10.162
Prometheus: 3.8.0
Unpoller: 2.19.0


DPI enabled in Unifi Network:

<img width="501" height="71" alt="Image" src="https://github.com/user-attachments/assets/0f143c4b-0fe6-48a3-a981-2032e96c5c00" />


DPI enabled in up.conf:

<img width="194" height="49" alt="Image" src="https://github.com/user-attachments/assets/bc47ac4a-daf2-494e-a96f-55fb09cd2bca" />


The "USW Insights" dashboard is also empty, as it probably tries to find a USW device, but my device is a UXG gateway.

The other dashboards are fine.

**Comment by bondskin** [comment]
@euri911 , regarding USW Dashboard:
I needed to remove a few fields from the SELECT statement, then it worked.

**Comment by bondskin** [comment]
I saw the first glimpse of hope in 2.21.0 (it's Christmas after all) in regards of DPI

"First working version DPI metrics and traffic exported"
https://github.com/unpoller/unpoller/commit/0b9d3de5cca2659ff7f8cdfd12f3ee4714fc959b

The Grafana dashboard is still empty but I had not time yet to look into it deeper.

**Comment by brngates98** [comment]
I believe I have accidentally resolved DPI with my Remote API commit today. I have all visualizations populated currently.

<img width="2048" height="1059" alt="Image" src="https://github.com/user-attachments/assets/298e41ce-7349-44f4-86e4-05c0a0c57e9d" />

<img width="2048" height="1062" alt="Image" src="https://github.com/user-attachments/assets/f7d26de5-6f51-4f9a-9c77-36c64148e7a7" />

**Comment by platinummonkey** [comment]
v2.22.0 should include that change, also shipping v2.23.0 now which includes some other fixes

**Comment by bondskin** [comment]
I just updated to 2.24.0 and set
save_dpi = true
but still not seeing DPI data in Grafana DPI dashboard.

**Comment by daxy01** [comment]
You need to do a bit more... Source: [reddit post](https://www.reddit.com/r/Ubiquiti/comments/1qmruye/monitoring_unifi_with_unpoller_just_got_way/?share_id=kLR30Wj1CIc7pjqRIeP-i&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1):
**Getting your API key**
Go to unifi.ui.com, sign in, then Settings → API Keys and create one. Just drop it in your config and you're good to go.

If you're using UniFi organizations or fabrics, you'll use yourorg.ui.com instead of unifi.ui.com. Same process though - Settings → API Keys.

Note: The API key is _not_ under you controller, but under your Site!!!

Then you need to also edit your up.conf file:
```
[unifi]
remote = true
remote_api_key = "<YOUR API KEY>"

```
After this, restart unpoller and the data will be gathered (at least in my case) 😀 

PS, great work @platinummonkey !!!!

**Comment by bondskin** [comment]
thanks @daxy01 , 
I am using the API already as per my up.conf

```
[unifi.defaults]
api_key = "yxz"

```

now I added as per your suggestion
```
remote = true
  remote_api_key = "xyzzy"
```

but no change.

log:
```
2026/01/26 11:18:34 [INFO] Configured UniFi Controller 1 of 1:
2026/01/26 11:18:34 [INFO]    => Mode: Remote
2026/01/26 11:18:34 [INFO]    => URL: https://192.168.2.1/ (verify SSL: false, timeout: 1m0s)
2026/01/26 11:18:34 [INFO]    => Version:  (9fe5fc40-6352-5a4e-92c7-984ac1e49a8e)
2026/01/26 11:18:34 [INFO]    => API Key: true
2026/01/26 11:18:34 [INFO]    => Hash PII false / Drop PII false / Poll Sites: all
2026/01/26 11:18:34 [INFO]    => Save Sites true / Save DPI true (metrics)
2026/01/26 11:18:34 [INFO]    => Save Events false / Save Syslog false / Save IDs false (logs)
2026/01/26 11:18:34 [INFO]    => Save Alarms false / Anomalies false / Protect Logs false (thumbnails: false)
2026/01/26 11:18:34 [INFO]    => Save Rogue APs: false
2026/01/26 11:18:34 [INFO]    => Save Traffic false
2026/01/26 11:18:34 [INFO] Prometheus is enabled
2026/01/26 11:18:34 [INFO] InfluxDB enabled
2026/01/26 11:18:34 [INFO] Poller->InfluxDB started, version: 1, interval: 1m0s, dp: false, db: unpoller, url: http://influxdb:8086, bucket: , org: 
2026/01/26 11:18:34 [INFO] Prometheus exported at http://0.0.0.0:9130/ - namespace: unpoller
2026/01/26 11:19:35 [INFO] UniFi Metrics Recorded. Site: 1, Client: 53, Gateways: 1, UAP: 5, USW: 5, IDs/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 1/0, Point: 137, Fields: 3973, Bytes: 110610, Err: 0, Dur: 250ms
```

**Comment by daxy01** [comment]
It seems unpoller still tries to connect locally (see URL).
Try commenting the lines starting with url, user and pass and also remove the API_key from the unifi.defaults section
As I mentioned before, get the API from unifi.ui.com, under Site Manager (menu bar on the left), under Settings. **Not** clicking on the AP icon on the top and then setting an API under Integrations (that one really doesn't work, took me some time to figure out).

The logs should say something like this when Remote API is successfully used:
```
2026/01/26 09:58:29 [INFO] Discovered console <My Console Name> with 1 site(s): [Default]
2026/01/26 09:58:29 [INFO] Discovered 1 remote controller(s)
2026/01/26 09:58:31 [INFO] Found 1 site(s) on controller https://api.ui.com/v1/connector/consoles/<some UUID>

```

Oh, and then finally, in the Grafana Dashboard I had to change the Site in the top bar from Default to my console's name 😀 Took me 5 minutes as well, lol.

Good luck!

**Comment by ChristianSatzky** [comment]
I've almost got it working now. 
However, the client DPI dashboard still doesn't make much sense. Host names are only displayed with long numbers and number combinations, and Totals by Category is not yet optimal either.
Does anyone happen to be using Influx 1.8 and could share their dashboard?
Perhaps a screenshot of the variables would also help.
I would appreciate any help.

<img width="2150" height="982" alt="Image" src="https://github.com/user-attachments/assets/c61e6308-9344-4229-aee7-1a615c814ace" />

Edit: The issue with the hostname has been resolved. I accidentally enabled hash_pii in up.conf.

**Comment by davepgreene** [comment]
Trying to get this working and I'm getting a 403 when trying to make an API call to the console proxy. I'm running OS Server 5.0.6 with network application 10.1.85 so I'm not quite sure what's going on. Anyone else run into this?

**Comment by lslamp** [comment]
This is incredible new that you have managed to get this to work. I have been doing a lot of research into this and even if all my config is correct I still did not see any data. What I did manage to understand is that the matrixes were being sent but they were failing silently, because the data packets seemed to be empty. No errors were shown.

My concern is unifi have now decided that they will stop supporting the Network Application and they they will only move forward with the Unifi OS.

I do not want to upgrade but have been told that the Network Application will become deprecated in the near future.

Does anyone know what the effect will be, will there be any improvements where DPI data might work.

Thanks
Lawrence

**Comment by lslamp** [comment]
I have been trying to understand why I am not seeing data, but I have hit a brick wall and have no clue where to turn now.

I have all the setting that are suggested.
in the up.conf file I have the following.

I have checked the logs and I see no errors or anything that is strange.
What does concern me is the following rows.

Polling Controller, retreiving UniFi Clients, site ICANH (default)
Requesting https://127.0.0.1:8443/api/s/default/stat/sta, with params: false, cookies: 1
Requested https://127.0.0.1:8443/api/s/default/stat/sta: elapsed 4ms, returned 31016 bytes
Polling Controller, retreiving UniFi Clients, site ICANR (25gzhpfg)
Requesting https://127.0.0.1:8443/api/s/25gzhpfg/stat/sta, with params: false, cookies: 1
Requested https://127.0.0.1:8443/api/s/25gzhpfg/stat/sta: elapsed 3ms, returned 31179 bytes
Requesting https://127.0.0.1:8443/api/s/default/stat/device, with params: false, cookies: 1
Requested https://127.0.0.1:8443/api/s/default/stat/device: elapsed 25ms, returned 179895 bytes

I see that there is some data but I cannot find where this data is being inserted into the database.

Below is a query from one of the panels. As you can see there is a table called clientdpi, when I open influx, and use the unifi database, I run show measurements I do not see a table clientdpi. This does not seem to be created.

SELECT last("rx_bytes")+last("tx_bytes") FROM "clientdpi" WHERE ("category" =~ /^${Category:regex}$/ AND "source" =~ /^${Controller:regex}$/ AND "site_name" =~ /^${Site:regex}$/ AND "name" =~ /^${Client:regex}$/ AND "application" != 'TOTAL') AND $timeFilter GROUP BY "application", "category"


below is an extract from my debug logs.
Collecting controller data: https://127.0.0.1:8443 ()
Polling controller: https://127.0.0.1:8443 ()
Requesting https://127.0.0.1:8443/api/stat/sites, with params: false, cookies: 1
Requested https://127.0.0.1:8443/api/stat/sites: elapsed 7ms, returned 4519 bytes
Found 2 site(s): default,25gzhpfg
Polling Controller, retreiving Site DPI data, site ICANH (default)
Requesting https://127.0.0.1:8443/api/s/default/stat/sitedpi, with params: true, cookies: 1
Requested https://127.0.0.1:8443/api/s/default/stat/sitedpi: elapsed 1ms, returned 32 bytes
Polling Controller, retreiving Site DPI data, site ICANR (25gzhpfg)
Requesting https://127.0.0.1:8443/api/s/25gzhpfg/stat/sitedpi, with params: true, cookies: 1
Requested https://127.0.0.1:8443/api/s/25gzhpfg/stat/sitedpi: elapsed 1ms, returned 32 bytes
Polling Controller, retreiving Client DPI data, site ICANH (default)
Requesting https://127.0.0.1:8443/api/s/default/stat/stadpi, with params: true, cookies: 1
Requested https://127.0.0.1:8443/api/s/default/stat/stadpi: elapsed 1ms, returned 30 bytes
Polling Controller, retreiving Client DPI data, site ICANR (25gzhpfg)
Requesting https://127.0.0.1:8443/api/s/25gzhpfg/stat/stadpi, with params: true, cookies: 1
Requested https://127.0.0.1:8443/api/s/25gzhpfg/stat/stadpi: elapsed 1ms, returned 30 bytes
Polling Controller, retreiving UniFi Clients, site ICANH (default)
Requesting https://127.0.0.1:8443/api/s/default/stat/sta, with params: false, cookies: 1
Requested https://127.0.0.1:8443/api/s/default/stat/sta: elapsed 4ms, returned 31016 bytes
Polling Controller, retreiving UniFi Clients, site ICANR (25gzhpfg)
Requesting https://127.0.0.1:8443/api/s/25gzhpfg/stat/sta, with params: false, cookies: 1
Requested https://127.0.0.1:8443/api/s/25gzhpfg/stat/sta: elapsed 3ms, returned 31179 bytes
Requesting https://127.0.0.1:8443/api/s/default/stat/device, with params: false, cookies: 1
Requested https://127.0.0.1:8443/api/s/default/stat/device: elapsed 25ms, returned 179895 bytes
Unmarshalling Device Type: uap, Model: UAP6MP, site ICANH (default)
Unmarshalling Device Type: uxg, Model: UXGB, site ICANH (default)
Unmarshalling Device Type: usw, Model: US8P60, site ICANH (default)
Unmarshalling Device Type: uap, Model: UAP6MP, site ICANH (default)
Unmarshalling Device Type: usw, Model: US8P60, site ICANH (default)
Unmarshalling Device Type: usw, Model: US24P250, site ICANH (default)
Unmarshalling Device Type: usw, Model: US8, site ICANH (default)
Unmarshalling Device Type: uap, Model: U7MP, site ICANH (default)
Unmarshalling Device Type: usw, Model: US8, site ICANH (default)
Unmarshalling Device Type: usw, Model: US8, site ICANH (default)
Unmarshalling Device Type: usw, Model: US8, site ICANH (default)
Unmarshalling Device Type: usw, Model: US8P60, site ICANH (default)

Any ideas?

Thanks
Lawrence

**Comment by daxy01** [comment]
@lslamp Short story is your unpoller is collecting data from your local controller while you should pull the Cloud environment.
Check my previous posts on obtaining (the correct) API key and use that. When you (re-)start unpoller, you'll see something like this:
`2026/01/26 09:58:29 [INFO] Discovered console <My Console Name> with 1 site(s): [Default]
2026/01/26 09:58:29 [INFO] Discovered 1 remote controller(s)
2026/01/26 09:58:31 [INFO] Found 1 site(s) on controller https://api.ui.com/v1/connector/consoles/<some UUID>`

If you see this line, then you know your unpoller is trying local instead of cloud:
`2026/01/26 11:18:34 [INFO]    => URL: https://192.168.2.1/ (verify SSL: false, timeout: 1m0s)`

**Comment by lslamp** [comment]
@daxy01 thank you for responding.
In truth I would like stats for both gateway devices. As you can see I have 2 sites in my config. Both are run on the same controller.
I think but am not sure, because I am using only a self-hosted solution and not online in the management portal, this might be causing some confusion. 
I do not have a cloud environment.
My first site is at a DC and my second site is at home. The controller is on a VM in the DC.
I was hoping that this would work ... but hey ho.
For clarification. I have added an API key that I generated on my ui portal, but how does that work in my sites are not listed?

Thanks
Lawrence

**Comment by ngreatorex** [comment]
I've switched to using the remote API but I'm still not seeing client DPI stats:

```
2026/03/25 12:38:27 [INFO] Loading Configuration File: /etc/unpoller/up.conf
2026/03/25 12:38:27 [INFO] UniFi Poller v2.38.0 Starting Up! PID: 1
2026/03/25 12:38:27 [INFO] Remote API mode enabled, discovering controllers...
2026/03/25 12:38:27 [INFO] Discovering remote UniFi consoles...
2026/03/25 12:38:28 [INFO] Found 1 Network-capable console(s) via remote API
2026/03/25 12:38:33 [INFO] Discovered console Cloud Gateway Max with 1 site(s): [Default]
2026/03/25 12:38:33 [INFO] Discovered 1 remote controller(s)
2026/03/25 12:38:35 [INFO] Found 1 site(s) on controller https://api.ui.com/v1/connector/consoles/<redacted>:<redacted>: default (Default)
2026/03/25 12:38:35 [INFO] Configured UniFi Controller 1 of 1:
2026/03/25 12:38:35 [INFO]    => Mode: Remote (Console: <redacted>:<redacted>)
2026/03/25 12:38:35 [INFO]    => URL: https://api.ui.com/v1/connector/consoles/<redacted>:<redacted> (verify SSL: false, timeout: 1m0s)
2026/03/25 12:38:35 [INFO]    => Version:  (c29ebb92-fa9e-5bb0-a055-c14ce75a8429)
2026/03/25 12:38:35 [INFO]    => API Key: true
2026/03/25 12:38:35 [INFO]    => Hash PII false / Drop PII false / Poll Sites: Default
2026/03/25 12:38:35 [INFO]    => Save Sites true / Save DPI true (metrics)
2026/03/25 12:38:35 [INFO]    => Save Events false / Save Syslog false / Save IDs false (logs)
2026/03/25 12:38:35 [INFO]    => Save Alarms false / Anomalies false / Protect Logs false (thumbnails: false)
2026/03/25 12:38:35 [INFO]    => Save Rogue APs: true
2026/03/25 12:38:35 [INFO]    => Save Traffic false
2026/03/25 12:38:35 [INFO] Prometheus is enabled
2026/03/25 12:38:35 [INFO] InfluxDB enabled
2026/03/25 12:38:35 [INFO] Poller->InfluxDB started, version: 2, interval: 30s, dp: false, db: , url: http://influxdb.lan, bucket: UniFi, org: <redacted>
2026/03/25 12:38:35 [INFO] Prometheus exported at http://0.0.0.0:9130/ - namespace: unpoller
2026/03/25 12:39:29 [INFO] UniFi Metrics Recorded. Site: 1, Client: 75, Gateways: 1, UAP: 2, USW: 1, IDs/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 1/0, Point: 897, Fields: 10019, Bytes: 426964, Err: 0, Dur: 5.563s
2026/03/25 12:39:51 [INFO] UniFi Metrics Recorded. Site: 1, Client: 75, Gateways: 1, UAP: 2, USW: 1, IDs/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 1/0, Point: 896, Fields: 10010, Bytes: 426646, Err: 0, Dur: 606ms
2026/03/25 12:40:20 [INFO] UniFi Metrics Recorded. Site: 1, Client: 75, Gateways: 1, UAP: 2, USW: 1, IDs/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 1/0, Point: 895, Fields: 10001, Bytes: 426105, Err: 0, Dur: 470ms
2026/03/25 12:40:50 [INFO] UniFi Metrics Recorded. Site: 1, Client: 75, Gateways: 1, UAP: 2, USW: 1, IDs/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 1/0, Point: 895, Fields: 10001, Bytes: 425924, Err: 0, Dur: 487ms
```

As you can see the DPI Client is 0. 

Are there any settings that might need to be changed in UniFi Network?
Do I need to change anything in up.conf other than the remote and api_key values?

**Comment by ngreatorex** [comment]
Ah never mind, I have fixed it. It seems that you need `save_traffic = true` as well as `save_dpi = true` for it to work.

**Comment by lslamp** [comment]
@ngreatorex 
I am still not clear.... Looking into my unpoller.log file I do not see the same as you are showing.

Below is my up.conf file.

cat /etc/unpoller/up.conf
# Unpoller v2 primary configuration file. TOML FORMAT #
###########################################################
[poller]
  debug = true
  quiet = false
  plugins = []

#### OUTPUTS
# If you don't use an output, you can disable it.
[influxdb]
  disable = false
  url  = "http://127.0.0.1:8086"
  user = "unifipoller"
  pass = "xxxxxxxxxx"
  db = "unifi"
  verify_ssl = false
  interval = "30s"
  dead_ports = false

#### INPUTS
[unifi]
  dynamic = false
  remote = true
  remote_api_key = "xxxxxxxxXXXXxxxXXxxn6-vzqM8Df1"

[unifi.defaults]
  url = "https://127.0.0.1:8443"
  user = "unifipoller"
  pass = "xxxxxxxx"
  sites = ["all"]
  save_sites = true
  hash_pii = false
  save_ids = false
  save_events = false
  save_alarms = false
  save_anomalies = false
  save_dpi = true
  save_traffic = true
  save_rogue = false
  verify_ssl = false
  ssl_cert_paths = []

below is what I see in the unpoller.log file. 

=> URL: https://127.0.0.1:8443 (verify 12 false)
=> Version: 10.1.89 (58fa3712-deca-4b2b-a8c1-649b8ddea6e1) 12
=> Username: unifipoller (has 12 true)
=> Hash PII false 12 Drop
=> Save Sites true 12 Save
=> Save Events false 12 Save
=> Save Alarms false 12 Anomalies
=> Save Rogue APs: 12
=> URL: https://127.0.0.1:8443 (verify 12 false)
=> Version: 10.1.89 (58fa3712-deca-4b2b-a8c1-649b8ddea6e1) 12
=> Username: unifipoller (has 12 true)
=> Hash PII false 12 Drop
=> Save Sites true 12 Save
=> Save Events false 12 Save
=> Save Alarms false 12 Anomalies
=> Save Rogue APs: 12


I am missing the following.

2026/03/25 12:38:27 [INFO] Loading Configuration File: /etc/unpoller/up.conf
2026/03/25 12:38:27 [INFO] UniFi Poller v2.38.0 Starting Up! PID: 1
2026/03/25 12:38:27 [INFO] Remote API mode enabled, discovering controllers...
2026/03/25 12:38:27 [INFO] Discovering remote UniFi consoles...
2026/03/25 12:38:28 [INFO] Found 1 Network-capable console(s) via remote API
2026/03/25 12:38:33 [INFO] Discovered console Cloud Gateway Max with 1 site(s): [Default]
2026/03/25 12:38:33 [INFO] Discovered 1 remote controller(s)
2026/03/25 12:38:35 [INFO] Found 1 site(s) on controller https://api.ui.com/v1/connector/consoles/<redacted>:<redacted>: default (Default)
2026/03/25 12:38:35 [INFO] Configured UniFi Controller 1 of 1:
2026/03/25 12:38:35 [INFO]    => Mode: Remote (Console: <redacted>:<redacted>)
2026/03/25 12:38:35 [INFO]    => URL: https://api.ui.com/v1/connector/consoles/<redacted>:<redacted> (verify SSL: false, timeout: 1m0s)
2026/03/25 12:38:35 [INFO]    => Version:  (c29ebb92-fa9e-5bb0-a055-c14ce75a8429)
2026/03/25 12:38:35 [INFO]    => API Key: true

Could this also be because I have the site in my local network on the same ipaddress range and not remote? Should I remove the remote=true and remote_API_key.

Thanks
Lawrence

**Comment by ngreatorex** [comment]
@lslamp 

You are still connecting locally. You need to remove the `url`, `user` and `pass` entries from the `[unifi.defaults]` section in your config.

PS. For future comments, it's best if you put things like config files and logs in "code" sections in the comment editor (press the <> button at the top right of the comment box or manuall add ``` before and after the block of lines)

**Comment by lslamp** [comment]
@ngreatorex  Sorry for the misunderstanding, I will try to do that is the future with the "code".

I have removed the 3 items but that has made no difference. It still seems that the database table is not being created. What am I doing wrong?

Thanks
Lawrence

**Comment by ngreatorex** [comment]
@lslamp 

What is your log showing now? Does it still show `URL: https://127.0.0.1:8443/`?

If so, please post the contents of your up.conf now but in a "code" section so the formatting doesn't go weird 🙂

**Comment by lslamp** [comment]
I am not very familiar with markdown coding. I will try.

```[poller]
  debug = true
  quiet = false
  plugins = []

#### OUTPUTS
# If you don't use an output, you can disable it.
[influxdb]
  disable = false
  url  = "http://127.0.0.1:8086"
  user = "unifipoller"
  pass = "xxxxxxxxxxx"
  db = "unifi"
  verify_ssl = false
  interval = "30s"
  dead_ports = false

#### INPUTS
[unifi]
  dynamic = false
#  remote = true
#  remote_api_key = "xxxxxxxxxxxxxxxxxxx-vzqM8Df1"

[unifi.defaults]
  sites = ["all"]
  save_sites = true
  hash_pii = false
  save_ids = false
  save_events = false
  save_alarms = false
  save_anomalies = false
  save_dpi = true
  save_traffic = true
  save_rogue = false
  verify_ssl = false
  ssl_cert_paths = []
```

extract from the log file

```
2026-03-25T15:28:09.738679+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:09 [INFO] Loading Configuration File: /etc/unpoller/up.conf
Debug Logging Enabled
2026-03-25T15:28:09.743229+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:09.743122 start.go:104: [INFO] UniFi Poller v2.11.2 Starting Up! PID: 30224
initializing 1 inputs
inititalizing input... unifi
Requesting https://127.0.0.1:8443/ to determine API paths
Requesting https://127.0.0.1:8443/api/login, with params: true, cookies: 0
Requested https://127.0.0.1:8443/api/login: elapsed 1.704s, returned 30 bytes
Requesting https://127.0.0.1:8443/status, with params: false, cookies: 1
Requested https://127.0.0.1:8443/status: elapsed 1ms, returned 113 bytes
Authenticated with controller successfully, https://127.0.0.1:8443
Checking Controller Sites List
Requesting https://127.0.0.1:8443/api/stat/sites, with params: false, cookies: 1
Requested https://127.0.0.1:8443/api/stat/sites: elapsed 6ms, returned 4516 bytes
Found 2 site(s): default,25gzhpfg
2026-03-25T15:28:11.467973+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.467777 updateweb.go:196: [INFO] Found 2 site(s) on controller https://127.0.0.1:8443: default (ICANH), 25gzhpfg (ICANR)
2026-03-25T15:28:11.468114+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.467799 updateweb.go:196: [INFO] Configured UniFi Controller 1 of 1:
2026-03-25T15:28:11.468205+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.467819 updateweb.go:196: [INFO]    => URL: https://127.0.0.1:8443 (verify SSL: false)
2026-03-25T15:28:11.468271+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.467837 updateweb.go:196: [INFO]    => Version: 10.1.89 (58fa3712-deca-4b2b-a8c1-649b8ddea6e1)
2026-03-25T15:28:11.468351+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.467855 updateweb.go:196: [INFO]    => Username: unifipoller (has password: true)
2026-03-25T15:28:11.468466+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.467871 updateweb.go:196: [INFO]    => Hash PII false / Drop PII false / Poll Sites: all
2026-03-25T15:28:11.468544+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.467888 updateweb.go:196: [INFO]    => Save Sites true / Save DPI true (metrics)
2026-03-25T15:28:11.468607+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.467904 updateweb.go:196: [INFO]    => Save Events false / Save IDS false (logs)
2026-03-25T15:28:11.468669+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.467919 updateweb.go:196: [INFO]    => Save Alarms false / Anomalies false (logs)
2026-03-25T15:28:11.468728+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.467934 updateweb.go:196: [INFO]    => Save Rogue APs: false
input successfully initialized ... unifi
collecting input errors...
returning error: %!w(<nil>)
staring outputs
output plugin disabled for WebServer
output plugin disabled for datadog
output plugin enabled, starting run loop for influxdb
output plugin disabled for loki
output plugin enabled, starting run loop for prometheus
2026-03-25T15:28:11.470486+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.468243 logger.go:19: [INFO] Prometheus is enabled
2026-03-25T15:28:11.470675+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.468261 logger.go:19: [INFO] InfluxDB enabled
2026-03-25T15:28:11.470750+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.468466 logger.go:19: [INFO] Poller->InfluxDB started, version: 1, interval: 30s, dp: false, db: unifi, url: http://127.0.0.1:8086, bucket: , org:
2026-03-25T15:28:11.470960+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:11.470547 logger.go:19: [INFO] Prometheus exported at http://0.0.0.0:9130/ - namespace: unpoller
```

**Comment by ngreatorex** [comment]
@lslamp 
> I am not very familiar with markdown coding. I will try.
Worked great 🙂 

Your main problem is that you're using an old version:

> 2026-03-25T15:28:09.743229+01:00 ICANUNIFI unpoller[30224]: 2026/03/25 15:28:09.743122 start.go:104: [INFO] UniFi Poller v2.11.2 Starting Up! PID: 30224

The remote API support was only added in v2.22.0.

Once you've upgraded to a newer version, you should uncomment the `remote` and `remote_api_key` lines in the config file. Then the URL in the logs should change to one that starts `https://api.ui.com`

**Comment by lslamp** [comment]
@ngreatorex  what, am I using an older version of unpoller.

How do I upgrade to the latest version.

I appreciate your support.
Lawrence

**Comment by ngreatorex** [comment]
@lslamp depends how you installed it in the first place. Did you use Docker or a package, or the manual install?

If you used Docker you can just delete and recreate the container. If you used the package method, you should use the tools included with your OS. If you did a manual install you can just download the latest again.

More details of the steps can be found under https://unpoller.com/docs/install/gettingstarted.

**Comment by lslamp** [comment]
If I remember because it was a VERY long time ago now, I did a manual install.

Lawrence

**Comment by lslamp** [comment]
I figured it, I have no updated unpoller to the following version.

```
unpoller, version 2.38.0 (branch: HEAD (2f1e28c7d3f997de44ada2e2bf6f0d32ba965c79), revision: 1)
  build user:       goreleaser
  build date:       2026-03-24T02:12:22Z
  go version:       go1.26.1
  platform:         linux/amd64
  started:          2026-03-25 17:59:36.690416068 +0100 CET m=+0.003897296
```

I will check my up.conf file and see if I get data

Thanks again for your help and guidance

**Comment by lslamp** [comment]
I have now restarted and checked the db and hip hip horey I see the clientdpi table. so I assume that after some time I will start seeing data.
Thanks
Lawrence

**Comment by kbuggenhout** [comment]
Why do we need to use the api over the cloud? My system is not set up for cloud access, only local. I did create an api key, but i guess that wont work without cloud authentication. On 25 Mar 2026, at 18:08, lslamp ***@***.***> wrote:﻿lslamp left a comment (unpoller/unpoller#834)
I have now restarted and checked the db and hip hip horey I see the clientdpi table. so I assume that after some time I will start seeing data.
Thanks
Lawrence

**Comment by lslamp** [comment]
@ngreatorex I have data, you are a super star. THANK YOU

kbuggenhout
You do not need to use the API_KEY. I have a local controller. Ping me if you need help or info. I learnt from @ngreatorex that you have to have the latest version of the unpoller.

Lawrence

**Comment by kbuggenhout** [comment]
hi, 

interestingly, I upgraded to 2.38.0, checked my conf file, 
tested with login/pass and with local API-Key 

but I dont see DPI stats, dpi dashboard remains empty, 

and from what I can see in my influxdb there is no DPI tag keys / measurements / series / field keys that relate to dpi. 

any hints? 

thnx K 


Van: "lslamp" ***@***.***> 
Aan: "unpoller/unpoller" ***@***.***> 
Cc: "buggenhout" ***@***.***>, "Manual" ***@***.***> 
Verzonden: Woensdag 25 maart 2026 18:18:42 
Onderwerp: Re: [unpoller/unpoller] Empty DPI stats (Issue #834) 

lslamp left a comment [ https://github.com/unpoller/unpoller/issues/834#issuecomment-4128339721 | (unpoller/unpoller#834) ] 


[ https://github.com/ngreatorex | @ngreatorex ] I have data, you are a super star. THANK YOU 

kbuggenhout 
You do not need to use the API_KEY. I have a local controller. Ping me if you need help or info. I learnt from [ https://github.com/ngreatorex | @ngreatorex ] that you have to have the latest version of the unpoller. 

Lawrence

**Comment by lslamp** [comment]
There were two things that I had to change to get this to work. I have now used any API key at all.
The first thing I had to do was give the user uni(I created this one) admin privileges ..
I also had to update the unpoller app.

<img width="1000" height="49" alt="Image" src="https://github.com/user-attachments/assets/c7755283-0dd2-4ab5-a9c6-70ec92a7ccc5" />

below is my up.conf file
```
cat /etc/unpoller/up.conf
[poller]
  debug = false
  quiet = false
  plugins = []

#### OUTPUTS
# If you don't use an output, you can disable it.
[influxdb]
  disable = false
  url  = "http://127.0.0.1:8086"
  user = "uni"
  pass = "xxxxxxx"
  db = "unifi"
  verify_ssl = false
  interval = "30s"
  dead_ports = false

#### INPUTS
[unifi]
  dynamic = false

[unifi.defaults]
  sites = ["all"]
  save_sites = true
  hash_pii = false
  save_ids = false
  save_events = false
  save_alarms = false
  save_anomalies = false
  save_dpi = true
  save_traffic = true
  save_rogue = false
  verify_ssl = false
  ssl_cert_paths = []
```

something I forgot to mention. On the commandline,
influx
use unifi
show measurements

check to see if your have a table names clientapi. --> this is the table where the DPI stats are saved and read into the grafana dashboard. If that table is present then you should have data. if not then you will definitely not have data.
Let me know.

**Comment by kbuggenhout** [comment]
thnx, 

well my config looks almost the same ( except for login/pass / ip) 
restarted unpoller again.. but there is no clientdpi table in my influxdb 

do you mean admin priv's on the UDM? for the poller user ( in my case "poller") 

# Unpoller v2 primary configuration file. TOML FORMAT # 
########################################################### 

[poller] 
debug = false 
quiet = true 
log_unknown_types = true 
plugins = [] 

#### OUTPUTS 

[influxdb] 
disable = false 
url = "http://127.0.0.1:8086" 
user = "###########" 
pass = "###########" 
db = "unifi" 
verify_ssl = false 
interval = "30s" 
dead_ports = false 

#### INPUTS 

[unifi] 
dynamic = false 

[unifi.defaults] 
url = "########" 
user = "poller" 
pass = "###########" 
api_key = "###############################" 
sites = ["all"] 
save_sites = true 
hash_pii = false 
save_events = false 
save_syslog = false 
save_alarms = false 
save_anomalies = false 
save_dpi = true 
save_rogue = false 
verify_ssl = false 
ssl_cert_paths = [] 

but I dont get a clientdpi table/tag in influxdb 

all the rest works fine 

thnx K 


Van: "lslamp" ***@***.***> 
Aan: "unpoller/unpoller" ***@***.***> 
Cc: "buggenhout" ***@***.***>, "Manual" ***@***.***> 
Verzonden: Donderdag 26 maart 2026 11:12:46 
Onderwerp: Re: [unpoller/unpoller] Empty DPI stats (Issue #834) 

lslamp left a comment [ https://github.com/unpoller/unpoller/issues/834#issuecomment-4133318064 | (unpoller/unpoller#834) ] 


There were two things that I had to change to get this to work. I have now used any API key at all. 
The first thing I had to do was give the user uni(I created this one) admin privileges .. 
I also had to update the unpoller app. [ https://github.com/user-attachments/assets/c7755283-0dd2-4ab5-a9c6-70ec92a7ccc5 | image.png (view on web) ] 

below is my up.conf file 
cat /etc/unpoller/up.conf
[poller]
  debug = false
  quiet = false
  plugins = []

#### OUTPUTS
# If you don't use an output, you can disable it.
[influxdb]
  disable = false
  url  = "http://127.0.0.1:8086"
  user = "uni"
  pass = "xxxxxxx"
  db = "unifi"
  verify_ssl = false
  interval = "30s"
  dead_ports = false

#### INPUTS
[unifi]
  dynamic = false

[unifi.defaults]
  sites = ["all"]
  save_sites = true
  hash_pii = false
  save_ids = false
  save_events = false
  save_alarms = false
  save_anomalies = false
  save_dpi = true
  save_traffic = true
  save_rogue = false
  verify_ssl = false
  ssl_cert_paths = [] 


Let me know.

**Comment by kbuggenhout** [comment]
well no luck, 

config has been updated, unpoller connects to the controller fine. 

2026-03-26T19:40:24.034727+01:00 ##### unpoller[146759]: 2026/03/26 19:40:24.034639 updateweb.go:285: [DEBUG] Found 1 site(s): default 
2026-03-26T19:40:24.034808+01:00 ##### unpoller[146759]: 2026/03/26 19:40:24.034666 updateweb.go:285: [DEBUG] Polling Controller, retreiving Site DPI data, site Default (default) 
2026-03-26T19:40:24.034894+01:00 ##### unpoller[146759]: 2026/03/26 19:40:24.034695 updateweb.go:285: [DEBUG] Requesting https://##.##.##.##/proxy/network/api/s/default/stat/sitedpi, with params: true, 
2026-03-26T19:40:24.069074+01:00 ##### unpoller[146759]: 2026/03/26 19:40:24.068968 updateweb.go:285: [DEBUG] Requested https://##.##.##.##/proxy/network/api/s/default/stat/sitedpi: elapsed 34ms, returned 32 bytes 
2026-03-26T19:40:24.069156+01:00 ##### unpoller[146759]: 2026/03/26 19:40:24.069021 updateweb.go:285: [DEBUG] Found 1 SitesDPI entries 
2026-03-26T19:40:24.069233+01:00 ##### unpoller[146759]: 2026/03/26 19:40:24.069036 updateweb.go:285: [DEBUG] Polling Controller, retreiving Client DPI data, site Default (default) 
2026-03-26T19:40:24.069314+01:00 ##### unpoller[146759]: 2026/03/26 19:40:24.069063 updateweb.go:285: [DEBUG] Requesting https://##.##.##.##/proxy/network/api/s/default/stat/stadpi, with params: true, 
2026-03-26T19:40:24.079980+01:00 ##### unpoller[146759]: 2026/03/26 19:40:24.079884 updateweb.go:285: [DEBUG] Requested https://##.##.##.##/proxy/network/api/s/default/stat/stadpi: elapsed 11ms, returned 30 bytes 
2026-03-26T19:40:24.080072+01:00 ##### unpoller[146759]: 2026/03/26 19:40:24.079925 updateweb.go:285: [DEBUG] Found 0 ClientsDPI entries 
2026-03-26T19:40:24.080125+01:00 ##### unpoller[146759]: 2026/03/26 19:40:24.079941 updateweb.go:285: [DEBUG] Polling Controller, retreiving UniFi Clients, site Default (default) 

no data is returned, and no clientdpi measurement table is created. 

when I manually try to access the controller through the api 
I get a result code which says no error, but also no data returned.

controller is set to store DPI, that data is visible in the unifi network app... but thats it

{
  "meta": {
    "rc": "ok"
  },
  "data": [
    {

    }
  ]
}

k rgrds, K

**Comment by lslamp** [comment]
did you give the user poller admin rights within the unifi dashboard under the users?

This was what changed things for me ... I think

Lawrence

**Comment by lslamp** [comment]
kbuggenhout,

this has been bugging me that you are not seeing data, I have also searched the thread but could not find what I was looking for, but there was somewhere that someone told me that the data was not being extracted and added to the database, this was indicated by the fact that the return was only 32 bytes. see below.
``` 
2026-03-26T19:40:24.069074+01:00 ##### unpoller[146759]: 2026/03/26 19:40:24.068968 updateweb.go:285: [DEBUG] Requested https://##.##.##.##/proxy/network/api/s/default/stat/sitedpi: elapsed 34ms, **returned 32 bytes**
```
The other thing that I remembered was to add the following line to your up.conf file.

```
save_traffic = true
save_api = true
```
save_traffic is not there by default. this was thanks to @ngreatorex pointing this info out.

Try that and see what happens.
Lawrence

**Comment by platinummonkey** [comment]
`v2.39.0` should contain the fix for #985 on the dual config issue, thought about a way to fix both older and newer devices at the same time. Will need someone to upgrade and test it when they have a chance.

**Comment by lslamp** [comment]
I will upgrade and take a look see

Thanks
Lawrence

**Comment by lslamp** [comment]
I just upgraded 

unpoller -version
unpoller, version 2.39.0 (branch: HEAD (c596e82cf29d445cd6f239b78f99ac2081d52b87), revision: 1)
  build user:       goreleaser
  build date:       2026-03-28T14:44:47Z
  go version:       go1.26.1
  platform:         linux/amd64
  started:          2026-03-28 16:29:36.568959125 +0100 CET m=+0.004091233

Will have to leave it running to gather some stats. Is there anything in particular to check for to confirm the issue is resolved?

Lawrence

**Comment by platinummonkey** [comment]
I don't expect the dashboards to "just work", but someone to check that the raw data is now available in your output plugin

**Comment by davepgreene** [comment]
I'm on the latest version of network and using remote connectivity and while DPI stats in bytes are coming through, packets aren't. Is that something expected? I'm using the [Client DPI dashboard](https://grafana.com/grafana/dashboards/11310-unifi-poller-client-dpi-prometheus/).

**Comment by lslamp** [comment]
@davepgreene 
do you have the following two entries in your up.conf file?

save_traffic = true
save_api = true

and have you given the unpoller user in unifi admin privileges? and the latest version of unpoller solved my issues and I started getting most data. 
I am also missing the following:
Packets Transferred per category.
Transmit Bytes - TOTAL -- No data reported.
Transmit Bytes - SM-R945F -- no data (samsung watch)
Receive Bytes - SM-R945F -- no data
All below are showing a solid line on the bottom, I assume that there is no data to show but the connection is made.
Receive Packets Business Tools
Transmit Packets Business Tools
Receive Packets Database Tools
Transmit Packets Database Tools
Receive Packets Email Messaging
Transmit Packets Email Messaging
Receive Packets File Sharing
Transmit Packets File Sharing

<img width="800" height="577" alt="Image" src="https://github.com/user-attachments/assets/bff2a018-e2fe-4d12-b6d2-b0a9a6f6b132" />

Something that is more a question.
All the devices shown have a name of the data seen and a MAC address, can this be changed to show the hostname or device name and not the MAC Address.

<img width="800" height="578" alt="Image" src="https://github.com/user-attachments/assets/f810314f-490e-40b9-acfa-bc488a714f0c" />

Great Tool
Thanks for the hard work.
Lawrence
